name: Push micromamba docker image

on:
  push:
    tags:
      - '*'

jobs:
  build_docker_image_and_push:
    if: ${{ startsWith(github.ref, 'refs/tags/') && !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: olegtarasov/get-tag@v2.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push image
      run: |
        docker build . -t ghcr.io/olegtarasov/micromamba:$GIT_TAG_NAME -t ghcr.io/olegtarasov/micromamba:latest
        docker push ghcr.io/olegtarasov/micromamba:latest
